// <auto-generated />
using System;
using LaytonTemple.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonTemple.Migrations
{
    [DbContext(typeof(LaytonTempleContext))]
    [Migration("20220322171137_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("LaytonTemple.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentID");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentID = 1,
                            AppointmentTime = new DateTime(2022, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Johnson@johnson.com",
                            Name = "Johnson",
                            Phone = "1231234567",
                            Size = 3
                        },
                        new
                        {
                            AppointmentID = 2,
                            AppointmentTime = new DateTime(2022, 3, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Davidson@davidson.com",
                            Name = "Davidson",
                            Phone = "9879876543",
                            Size = 4
                        },
                        new
                        {
                            AppointmentID = 3,
                            AppointmentTime = new DateTime(2022, 3, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jackson@jackson.com",
                            Name = "Jackson",
                            Phone = "5555555555",
                            Size = 2
                        });
                });

            modelBuilder.Entity("LaytonTemple.Models.Time", b =>
                {
                    b.Property<int>("TimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SlotFilled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeID");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            TimeID = 1,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 2,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 3,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 4,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 5,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 6,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 7,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 8,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 9,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 10,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 11,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 12,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeID = 13,
                            SlotFilled = false,
                            TimeDescription = new DateTime(2022, 3, 28, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
