// <auto-generated />
using LaytonTemple.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonTemple.Migrations
{
    [DbContext(typeof(LaytonTempleContext))]
    [Migration("20220322040420_Seeded")]
    partial class Seeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("LaytonTemple.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentID");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentID = 1,
                            AppointmentTime = "1:00 PM",
                            Email = "Johnson@johnson.com",
                            Name = "Johnson",
                            Phone = "1231234567",
                            Size = 3
                        },
                        new
                        {
                            AppointmentID = 2,
                            AppointmentTime = "11:00 AM",
                            Email = "Davidson@davidson.com",
                            Name = "Davidson",
                            Phone = "9879876543",
                            Size = 4
                        },
                        new
                        {
                            AppointmentID = 3,
                            AppointmentTime = "5:00 PM",
                            Email = "Jackson@jackson.com",
                            Name = "Jackson",
                            Phone = "5555555555",
                            Size = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
